import { access, copyFile, mkdir, readFile, writeFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const androidRoot = path.join(root, 'android')
const resourcesRoot = path.join(androidRoot, 'app', 'src', 'main', 'res')
const capacitorCli = path.join(root, 'node_modules', '@capacitor', 'cli', 'bin', 'capacitor')
const npmCli = path.join(path.dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npm-cli.js')

function run(command, args, cwd = root) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, env: process.env, stdio: 'inherit', shell: false })
    child.once('error', reject)
    child.once('exit', code => code === 0 ? resolve() : reject(new Error(`${path.basename(command)} exited with code ${code}`)))
  })
}

async function syncLauncherIcons() {
  const legacySource = path.join(root, 'public', 'icons', 'icon-192.png')
  const adaptiveSource = path.join(root, 'public', 'icons', 'icon-512.png')
  const densities = ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']

  for (const density of densities) {
    const destination = path.join(resourcesRoot, `mipmap-${density}`)
    await mkdir(destination, { recursive: true })
    await Promise.all([
      copyFile(legacySource, path.join(destination, 'ic_launcher.png')),
      copyFile(legacySource, path.join(destination, 'ic_launcher_round.png')),
      copyFile(adaptiveSource, path.join(destination, 'ic_launcher_foreground.png')),
    ])
  }
}

async function ensureGeneratedCordovaPlaceholders() {
  const publicAssetsRoot = path.join(androidRoot, 'app', 'src', 'main', 'assets', 'public')
  const placeholders = new Map([
    ['cordova.js', "'use strict';\n// Generated by Capacitor sync: no Cordova bridge runtime is required.\nvoid 0;\n"],
    ['cordova_plugins.js', "'use strict';\n// Generated by Capacitor sync: no Cordova plugins are registered.\nvoid 0;\n"],
  ])

  for (const [name, generatedJavaScript] of placeholders) {
    const destination = path.join(publicAssetsRoot, name)
    const existing = await readFile(destination)
    if (existing.length === 0) await writeFile(destination, generatedJavaScript, 'utf8')
  }
}

await Promise.all([access(npmCli), access(capacitorCli)])
await run(process.execPath, [npmCli, 'run', 'build'])
await syncLauncherIcons()
await run(process.execPath, [capacitorCli, 'sync', 'android'])
await ensureGeneratedCordovaPlaceholders()
console.log('Synchronized production dist and VMT launcher resources into android')
