import { access, readFile, rm, writeFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const androidRoot = path.join(root, 'android')
const resourcesRoot = path.join(androidRoot, 'app', 'src', 'main', 'res')
const capacitorCli = path.join(root, 'node_modules', '@capacitor', 'cli', 'bin', 'capacitor')
const npmCli = path.join(path.dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npm-cli.js')
const brandGenerator = path.join(root, 'scripts', 'generate-brand-assets.ps1')

function run(command, args, cwd = root) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, env: process.env, stdio: 'inherit', shell: false })
    child.once('error', reject)
    child.once('exit', code => code === 0 ? resolve() : reject(new Error(`${path.basename(command)} exited with code ${code}`)))
  })
}

function pngDimensions(bytes) {
  const signature = [137, 80, 78, 71, 13, 10, 26, 10]
  if (bytes.length < 24 || !signature.every((value, index) => bytes[index] === value)) {
    throw new Error('Android brand asset is not a valid PNG')
  }
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) }
}

async function generateAndValidateBrandResources() {
  if (process.platform === 'win32') {
    await run('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', brandGenerator])
  }

  const launcherSizes = new Map([['mdpi', 48], ['hdpi', 72], ['xhdpi', 96], ['xxhdpi', 144], ['xxxhdpi', 192]])
  const foregroundSizes = new Map([['mdpi', 108], ['hdpi', 162], ['xhdpi', 216], ['xxhdpi', 324], ['xxxhdpi', 432]])
  for (const [density, size] of launcherSizes) {
    for (const name of ['ic_launcher.png', 'ic_launcher_round.png']) {
      const dimensions = pngDimensions(await readFile(path.join(resourcesRoot, `mipmap-${density}`, name)))
      if (dimensions.width !== size || dimensions.height !== size) throw new Error(`${density}/${name} must be ${size}x${size}`)
    }
    const foreground = pngDimensions(await readFile(path.join(resourcesRoot, `mipmap-${density}`, 'ic_launcher_foreground.png')))
    const foregroundSize = foregroundSizes.get(density)
    if (foreground.width !== foregroundSize || foreground.height !== foregroundSize) {
      throw new Error(`${density}/ic_launcher_foreground.png must be ${foregroundSize}x${foregroundSize}`)
    }
  }
}

async function ensureGeneratedCordovaPlaceholders() {
  const publicAssetsRoot = path.join(androidRoot, 'app', 'src', 'main', 'assets', 'public')
  await rm(path.join(publicAssetsRoot, 'downloads'), { recursive: true, force: true })

  const placeholders = new Map([
    ['cordova.js', "'use strict';\n// Generated by Capacitor sync: no Cordova bridge runtime is required.\nvoid 0;\n"],
    ['cordova_plugins.js', "'use strict';\n// Generated by Capacitor sync: no Cordova plugins are registered.\nvoid 0;\n"],
  ])

  for (const [name, generatedJavaScript] of placeholders) {
    const destination = path.join(publicAssetsRoot, name)
    const existing = await readFile(destination)
    if (existing.length === 0) await writeFile(destination, generatedJavaScript, 'utf8')
  }
}

await Promise.all([access(npmCli), access(capacitorCli), access(brandGenerator)])
await generateAndValidateBrandResources()
await run(process.execPath, [npmCli, 'run', 'build'])
await run(process.execPath, [capacitorCli, 'sync', 'android'])
await ensureGeneratedCordovaPlaceholders()
console.log('Synchronized production dist and VMT branding resources into android')
